title: andras marton dot com
email: mail@andrasmarton.com
description: >-
  My personal blog covering cyber security, programming and technology.
baseurl: ""
url: "https://www.andrasmarton.com"
include:
  - .well-known
exclude:
  - README.md
  - Makefile
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: :slug/
