title: andras marton personal site
email: mail@marton.pw
description: >-
  My personal blog covering cyber security, programming and technology.
baseurl: ""
url: "https://marton.pw"
include:
  - .well-known
exclude:
  - README.md
  - Makefile
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: :slug/
